- name: Configuration of workstations and laptops
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        state: latest
      when: ansible_distribution == "CentOS"
    - name: Install necessary packages
      yum:
        name:
          - htop
          - vim
          - iftop
          - net-snmp
          - net-tools
          - wget
          - ntp
          - ipa-client
        state: present
    - name: Enable SELinux
      selinux:
        policy: targeted
        state: enforcing
    - name: Update everything
      yum:
        name: '*'
        state: latest
    - name: Create the GNOME Display Manager Configuration Directory
      file:
        path: /etc/dconf/db/gdm.d
        state: directory
    - name: Create a configuration file to hide the user list on the lock screen
      copy:
        src: files/gdm.d-01-login-screen
        dest: /etc/dconf/db/gdm.d/01-login-screen
    - name: Create the GDM DCONF profile
      copy:
        src: files/etc-dconf-profile-gdm
        dest: /etc/dconf/profile/gdm
      register: dconf
    - name: Update DCONF if changed
      shell: dconf update
      when: dconf.changed
